### ISSUE TITLE
Allow `new` command in non-empty dirs

### ISSUE THREAD

**Issue by ivangretsky** [wirecli/wire-cli#14]
Good day, @flydev-fr ! Thanks for this tool once again!

You [taught me](https://github.com/wirecli/wire-cli/issues/8#issuecomment-2089916139) how to install and use wirecli non-globally. I think that it is pretty cool way to use it not only for the development. Rockshell uses this way of installation by default.

The issue with this now is `new` command wouldn't work this way, as it requires an empty folder for installation. Could we remove this restriction? What do you think?

**Comment by flydev-fr** [comment]
Hi Ivan, I will implement it - I have to check my dev version as I think I already did it.

**Comment by ivangretsky** [comment]
Good day, @flydev-fr ! 
I am testing this once again and the issue is still here. Is it possible that you could find some time to look into it?

**Comment by flydev-fr** [comment]
Hey @ivangretsky to be honest, I kinda forgot to look. I will fix it tomorrow on the morning. 

The line you linked could be removed but I prefer to make an option, I think it should be safer to stay with an empty dir required by default and adding something like a `--force` to bypass it.

**Comment by ivangretsky** [comment]
I guess that will be not just good enough but great!

**Comment by flydev-fr** [comment]
done @ivangretsky, feel free to re-open if you encounter an issue.

**Comment by flydev-fr** [comment]
Forgot to say that you can use it using force option:  `wirecli new --force`

**Comment by ivangretsky** [comment]
Thanks!
Checked it out - works as expected.

**Comment by flydev-fr** [comment]
Perfect 👍

Le lun. 9 sept. 2024 à 10:29, Ivan Gretsky ***@***.***> a
écrit :
