### ISSUE TITLE
Setting site/config.php with wire-cli

### ISSUE THREAD

**Issue by Clarity-Atlant** [wirecli/wire-cli#9]
Hello, @flydev-fr!

I found some problems with installing ProcessWire via wire-cli.

I think that the following should be added to the site/config.php file:

1. $config->tableSalt (salt);
2. $config->installed (installation date).

Can you please add it?

**Comment by flydev-fr** [comment]
Closing the issue as it's fixed, thanks for reporting it. feel free to re-open if something goes wrong.
